<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Admin_SRV-PC" ignored="2" name="Default test(failed)" tests="6" failures="1" timestamp="2022-04-11T16:53:49 IST" time="0.086" errors="0">
  <testcase name="Test2" time="0.01" classname="Listners.RetryFailedcases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="Listners.RetryFailedcases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="Listners.RetryFailedcases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.005" classname="Listners.RetryFailedcases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="Listners.RetryFailedcases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="Listners.RetryFailedcases">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at Listners.RetryFailedcases.Test2(RetryFailedcases.java:38)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test1" time="0.0" classname="Listners.RetryFailedcases">
    <ignored/>
  </testcase> <!-- Test1 -->
  <testcase name="Test3" time="0.0" classname="Listners.RetryFailedcases">
    <ignored/>
  </testcase> <!-- Test3 -->
</testsuite> <!-- Default test(failed) -->
